# Generated by Django 5.0.7 on 2024-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalystCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('domain', models.CharField(max_length=200, verbose_name='domain')),
                ('year_founded', models.CharField(max_length=20, verbose_name='year founded')),
                ('industry', models.CharField(max_length=250, verbose_name='industry')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('county', models.CharField(max_length=250, verbose_name='county')),
                ('current_employee', models.CharField(max_length=250, verbose_name='current_employee')),
                ('total_employee', models.CharField(max_length=250, verbose_name='total_employee')),
            ],
        ),
    ]
