# Generated by Django 5.0.7 on 2024-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalystcount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='catalystcount',
            name='county',
        ),
        migrations.AddField(
            model_name='catalystcount',
            name='country',
            field=models.CharField(blank=True, default='abc', max_length=250, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='catalystcount',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='linkedin url'),
        ),
        migrations.AddField(
            model_name='catalystcount',
            name='locality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='locality'),
        ),
    ]
