# Generated by Django 5.0.7 on 2024-07-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_catalystcount_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalystcount',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='country'),
        ),
    ]
