# Generated by Django 5.0.7 on 2024-07-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_catalystcount_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalystcount',
            name='current_employee',
        ),
        migrations.RemoveField(
            model_name='catalystcount',
            name='total_employee',
        ),
        migrations.AddField(
            model_name='catalystcount',
            name='employees_from',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='employees_from'),
        ),
        migrations.AddField(
            model_name='catalystcount',
            name='employees_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='employees_to'),
        ),
    ]
