name: DEV to QAT Rule

on:
  pull_request:
    branches:
      - QAT  # Trigger when a pull request targets QAT

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check Source Branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "DEV" ]]; then
            echo "Only merges from DEV to QAT are allowed."
            exit 1
          fi